// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// flasso_compressed_rep_cd_fit_cpp
List flasso_compressed_rep_cd_fit_cpp(NumericMatrix G, NumericMatrix B, IntegerVector donor_index, NumericVector y, NumericVector lambda, NumericVector feature_off, NumericVector Q_array, NumericVector group_multiplier, double alpha, double eps, int max_iter, NumericVector offset_vec);
RcppExport SEXP _TWiST_flasso_compressed_rep_cd_fit_cpp(SEXP GSEXP, SEXP BSEXP, SEXP donor_indexSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP feature_offSEXP, SEXP Q_arraySEXP, SEXP group_multiplierSEXP, SEXP alphaSEXP, SEXP epsSEXP, SEXP max_iterSEXP, SEXP offset_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type G(GSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type donor_index(donor_indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type feature_off(feature_offSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Q_array(Q_arraySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type group_multiplier(group_multiplierSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset_vec(offset_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(flasso_compressed_rep_cd_fit_cpp(G, B, donor_index, y, lambda, feature_off, Q_array, group_multiplier, alpha, eps, max_iter, offset_vec));
    return rcpp_result_gen;
END_RCPP
}
// flasso_rep_maxgrad_cell_cpp
double flasso_rep_maxgrad_cell_cpp(NumericMatrix G, NumericMatrix B, IntegerVector donor_index, NumericVector r, NumericVector center, NumericVector scale, NumericVector raw_T_array, NumericVector group_multiplier);
RcppExport SEXP _TWiST_flasso_rep_maxgrad_cell_cpp(SEXP GSEXP, SEXP BSEXP, SEXP donor_indexSEXP, SEXP rSEXP, SEXP centerSEXP, SEXP scaleSEXP, SEXP raw_T_arraySEXP, SEXP group_multiplierSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type G(GSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type donor_index(donor_indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type center(centerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type raw_T_array(raw_T_arraySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type group_multiplier(group_multiplierSEXP);
    rcpp_result_gen = Rcpp::wrap(flasso_rep_maxgrad_cell_cpp(G, B, donor_index, r, center, scale, raw_T_array, group_multiplier));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TWiST_flasso_compressed_rep_cd_fit_cpp", (DL_FUNC) &_TWiST_flasso_compressed_rep_cd_fit_cpp, 12},
    {"_TWiST_flasso_rep_maxgrad_cell_cpp", (DL_FUNC) &_TWiST_flasso_rep_maxgrad_cell_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_TWiST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
