# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

flasso_compressed_rep_cd_fit_cpp <- function(G, B, donor_index, y, lambda, feature_off, Q_array, group_multiplier, alpha, eps, max_iter, offset_vec) {
    .Call(`_TWiST_flasso_compressed_rep_cd_fit_cpp`, G, B, donor_index, y, lambda, feature_off, Q_array, group_multiplier, alpha, eps, max_iter, offset_vec)
}

flasso_rep_maxgrad_cell_cpp <- function(G, B, donor_index, r, center, scale, raw_T_array, group_multiplier) {
    .Call(`_TWiST_flasso_rep_maxgrad_cell_cpp`, G, B, donor_index, r, center, scale, raw_T_array, group_multiplier)
}

